on:
  push:
    branches: [master]
  pull_request:
  release:
    types:
    - created

name: CI
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: "yarn.lock,.git"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Tests with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run pretest
      # - run: yarn run test
      - name: Publish
        if: success() && startsWith( github.ref, 'refs/tags/releases/') && ${{ matrix.node-version }} == '14.x'
        run: |
          yarn install --dev
          yarn run deploy-vs -p ${{ secrets.VSCE_PAT }}
          yarn run deploy-ovsx -p ${{ secrets.OPEN_VSX_PAT }}